version: '3.8'

services:
  db:
    image: postgres:15
    container_name: foodgram_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: foodgram_backend
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_STATIC_ROOT: /app/static/backend/
    volumes:
      - static_volume:/app/static/backend/
      - media_volume:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: foodgram_frontend
    restart: always
    volumes:
      - static_volume:/app/build/static/
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25
    container_name: foodgram_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume: 