version: '3.3'

volumes:
  pg_data:
  static_volume:
  backend_static_volume:
  backend_media_volume:

services:
  db:
    image: postgres:13.3-alpine
    container_name: foodgram-db
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram-backend
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    env_file:
      - ./.env
    volumes:
      - backend_static_volume:/app/static/backend/
      - backend_media_volume:/app/media/
      - ../data:/app/fixtures
    depends_on:
      - db
    restart: always

  frontend:
    container_name: foodgram-front
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    volumes:
      - static_volume:/app/result_build/
    restart: always

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/usr/share/nginx/html/static
      - backend_static_volume:/usr/share/nginx/html/static/backend
      - backend_media_volume:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
