USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
MIN_COOKING_TIME_VALUE = 1
MIN_AMOUNT_VALUE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
